sudo: false
language: node_js
node_js:
  - '9'
cache:
  yarn: true
  directories:
    - ~/.npm
    - ~/.cache
notifications:
  email: false
before_script: yarn --cwd stories install
script: yarn validate
after_success: kcd-scripts travis-after-success
branches:
  only: master
